from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from ferreteria import views



urlpatterns = [
    path('',views.inicio, name='inicio'),
    path('recuperar_contrasena/', views.recuperar_contrasena, name='recuperar_contrasena'),
    path('reset_password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path("enviar-correo/", views.enviar_correo, name="enviar_correo"),
    path('productosdestacados/', views.productosdestacados, name='productosdestacados'),
    path('bticino/', views.bticino, name='bticino'),
    path('lexo/', views.lexo, name='lexo'),
    path('synthesi/', views.synthesi, name='synthesi'),
    path('smarthome/', views.smarthome, name='smarthome'),
    path('stanford/', views.stanford, name='stanford'),
    path('cablesevaflex/', views.cablesevaflex, name='cablesevaflex'),
    path('cordones/', views.cordones, name='cordones'),
    path('otrosconductores/', views.otrosconductores, name='otrosconductores'),
    path('volantes_adaptadores/', views.volantes_adaptadores, name='volantes_adaptadores'),
    path('terminales_conductores/', views.terminales_conductores, name='terminales_conductores'),
    path('abrazaderaspvc/', views.abrazaderaspvc, name='abrazaderaspvc'),
    path('curvaspvc/', views.curvaspvc, name='curvaspvc'),
    path('tuberiaspvc/', views.tuberiaspvc, name='tuberiaspvc'),
    path('abrazaderasemt/', views.abrazaderasemt, name='abrazaderasemt'),
    path('cajasemt/', views.cajasemt, name='cajasemt'),
    path('conectormet/', views.conectormet, name='conectormet'),
    path('conectorhub/', views.conectorhub, name='conectorhub'),
    path('coplasemt/', views.coplasemt, name='coplasemt'),
    path('curvasemt/', views.curvasemt, name='curvasemt'),
    path('terminalesemt/', views.terminalesemt, name='terminalesemt'),
    path('tuberiasemt/', views.tuberiasemt, name='tuberiasemt'),
    path('galvanizado/', views.galvanizado, name='galvanizado'),
    path('tuberiasflexibles_accesorios/', views.tuberiasflexibles_accesorios, name='tuberiasflexibles_accesorios'),
    path('accesoriosdemolduras/', views.accesoriosdemolduras, name='accesoriosdemolduras'),
    path('canaletas/', views.canaletas, name='canaletas'),
    path('molduras/', views.molduras, name='molduras'),
    path('accesoriobandeja/', views.accesoriobandeja, name='accesoriobandeja'),
    path('accesorioescalerilla/', views.accesorioescalerilla, name='accesorioescalerilla'),
    path('bandeja/', views.bandeja, name='bandeja'),
    path('escalerilla/', views.escalerilla, name='escalerilla'),
    path('fijaciones/', views.fijaciones, name='fijaciones'),
    path('tuercas/', views.tuercas, name='tuercas'),
    path('complementosaccesorios/', views.complementosaccesorios, name='complementosaccesorios'),
    path('contactores/', views.contactores, name='contactores'),
    path('diferenciales/', views.diferenciales, name='diferenciales'),
    path('automaticos/', views.automaticos, name='automaticos'),
    path('cajasempalme/', views.cajasempalme, name='cajasempalme'),
    path('cajas/', views.cajas, name='cajas'),
    path('gabinetes/', views.gabinetes, name='gabinetes'),
    path('tablerosembutido/', views.tablerosembutido, name='tablerosembutido'),
    path('tablerossobrepuesto/', views.tablerossobrepuesto, name='tablerossobrepuesto'),
    path('tablerosexterior/', views.tablerosexterior, name='tablerosexterior'),
    path('embutidos220/', views.embutidos220, name='embutidos220'),
    path('embutidos380/', views.embutidos380, name='embutidos380'),
    path('volantes220/', views.volantes220, name='volantes220'),
    path('volantes380/', views.volantes380, name='volantes380'),
    path('sobrepuestos220/', views.sobrepuestos220, name='sobrepuestos220'),
    path('sobrepuestos380/', views.sobrepuestos380, name='sobrepuestos380'),
    path('lamparas/', views.lamparas, name='lamparas'),
    path('ampolletasvintage/', views.ampolletasvintage, name='ampolletasvintage'),
    path('ampolletassmart/', views.ampolletassmart, name='ampolletassmart'),
    path('ampolletasgu10/', views.ampolletasgu10, name='ampolletasgu10'),
    path('ampolletase27/', views.ampolletase27, name='ampolletase27'),
    path('apliques/', views.apliques, name='apliques'),
    path('accesoriosiluminacion/', views.accesoriosiluminacion, name='accesoriosiluminacion'),
    path('proyectoresconsensor/', views.proyectoresconsensor, name='proyectoresconsensor'),
    path('proyectoressinsensor/', views.proyectoressinsensor, name='proyectoressinsensor'),
    path('proyectoressolares/', views.proyectoressolares, name='proyectoressolares'),
    path('panelesledcuadradoembutidos/', views.panelesledcuadradoembutidos, name='panelesledcuadradoembutidos'),
    path('panelesledcuadradosobrepuestos/', views.panelesledcuadradosobrepuestos, name='panelesledcuadradosobrepuestos'),
    path('panelesledredondoembutidos/', views.panelesledredondoembutidos, name='panelesledredondoembutidos'),
    path('panelesledredondosobrepuestos/', views.panelesledredondosobrepuestos, name='panelesledredondosobrepuestos'),
    path('tubosfluorescentes/', views.tubosfluorescentes, name='tubosfluorescentes'),
    path('tubosled/', views.tubosled, name='tubosled'),
    path('equipocanoa/', views.equipocanoa, name='equipocanoa'),
    path('equipoestanco/', views.equipoestanco, name='equipoestanco'),
    path('categorias_tienda/', views.categorias_tienda, name='categorias_tienda'),
    path('terminoscondiciones/', views.terminoscondiciones, name='terminoscondiciones'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
    path('carrito/', views.ver_carrito, name='ver_carrito'),
    path('agregar/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('eliminar/<int:item_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('finalizar-compra/', views.finalizar_compra, name='finalizar_compra'),
]
if settings.DEBUG:  # Solo en modo desarrolloA
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)