# Generated by Django 5.1.2 on 2024-12-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('sin_categoria', 'Sin Categoría'), ('bticino', 'Bticino'), ('lexo', 'Lexo'), ('synthesi', 'Synthesi'), ('smarthome', 'Smart Home'), ('stanford', 'Stanford'), ('cablesevaflex', 'Cables Evaflex'), ('cordones', 'Cordones'), ('otrosconductores', 'Otros Conductores'), ('volantes_adaptadores', 'Volantes y Adaptadores'), ('terminales_conductores', 'Terminales y Conductores'), ('abrazaderaspvc', 'Abrazaderas PVC'), ('curvaspvc', 'Curvas PVC'), ('tuberiaspvc', 'Tuberias PVC'), ('abrazaderasemt', 'Abrazaderas EMT'), ('cajasemt', 'Cajas EMT'), ('conectormet', 'Conector MET'), ('conectorhub', 'Conector HUB'), ('coplasemt', 'Coplas EMT'), ('curvasemt', 'Curvas EMT'), ('terminalesemt', 'Terminales EMT'), ('tuberiasemt', 'Tuberias EMT'), ('galvanizado', 'Galvanizado'), ('tuberiasflexibles_accesorios', 'Tuberias Flexibles y Accesorios'), ('accesoriosdemoldura', 'Accesorios de Moldura'), ('canaletas', 'Canaletas'), ('molduras', 'Molduras'), ('accesoriobandeja', 'Accesorios De Bandeja'), ('accesoriosescalerilla', 'Accesorios De Escalerilla'), ('bandeja', 'Bandeja'), ('escalerilla', 'Escalerilla'), ('equipoestanco', 'Equipos Estancos'), ('equipocanoa', 'Equipos Canoas'), ('tubosled', 'Tubos LED'), ('tubosfluorescentes', 'Tubos Fluorescentes'), ('panelesledredondosobrepuestos', 'Paneles LED Redondos Sobrepuestos'), ('panelesledredondoembutidos', 'Paneles LED Redondos Embutidos'), ('panelesledcuadradosobrepuestos', 'Paneles LED Cuadrados Sobrepuestos'), ('panelesledcuadradoembutidos', 'Paneles LED Cuadrados Embutidos'), ('proyectoresconsensor', 'Proyectores Con Sensor'), ('proyectoressinsensor', 'Proyectores Sin Sensor'), ('proyectoressolares', 'Proyectores Solares'), ('accesoriosiluminacion', 'Accesorios De Iluminacion'), ('apliques', 'Apliques'), ('ampolletase27', 'Ampolletas E27'), ('ampolletasgu10', 'Ampolletas GU10'), ('ampolletassmart', 'Ampolletas Smart'), ('ampolletasvintage', 'Ampolletas Vintage'), ('lamparas', 'Lamparas'), ('sobrepuestos380', 'Sobrepuestos 380V'), ('sobrepuestos220', 'Sobrepuestos 220V'), ('volantes380', 'Volantes 380V'), ('volantes220', 'Volantes 220V'), ('embutidos380', 'Embutidos 380V'), ('embutidos220', 'Embutidos 220V'), ('tablerosexterior', 'Tableros Exterior'), ('tablerossobrepuesto', 'Tableros Sobrepuestos'), ('tablerosembutido', 'Tableros Embutidos'), ('gabinetes', 'Gabinetes'), ('cajas', 'Cajas'), ('cajasempalme', 'Cajas De Empalme'), ('automaticos', 'Automaticos'), ('diferenciales', 'Diferenciales'), ('contactores', 'Contactores'), ('complementosaccesorios', 'Complementos y Accesorios'), ('tuercas', 'Tuercas'), ('fijaciones', 'Fijaciones')], default='Sin Categoria', max_length=50)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ferreteria.cotizacion')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Productos cotizados por el cliente',
            },
        ),
    ]
